import cam1 from '../../Assets/Imgdrones/cam1.webp'
import cam2 from '../../Assets/Imgdrones/cam2.webp'
import cam3 from '../../Assets/Imgdrones/cam3.webp'
import cam4 from '../../Assets/Imgdrones/cam4.webp'
import cam5 from '../../Assets/Imgdrones/cam5.webp'
import cam51 from '../../Assets/Imgdrones/cam51.webp'
import cam52 from '../../Assets/Imgdrones/cam52.webp' 
import cam6 from '../../Assets/Imgdrones/cam6.webp'
import cam7 from '../../Assets/Imgdrones/cam7.webp'
import cam8 from '../../Assets/Imgdrones/cam8.webp'

export const dronesdata = [
    {
        "id": 'D1',
        "title":'Shak Outdoor Spotlight Security Camera',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam1,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'D2',
        "title":'H1C Indoor Wireless 1080p Network Security Camera',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"NO-Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam2,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'D3',
        "title":'Wave Mini 4 Quadcopter With Remote Controller',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam3,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'D4',
        "title":'Pantony DSLR Old School Camera With 18-55mm Lens',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam4,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'D5',
        "title":'HKI Tech Quadcopter Drone With 360 Camera & Controller',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam5,
        thumbnail2: cam51,
        thumbnail3: cam52,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'D6',
        "title":'Megapixel Waterproof Mini Digital Camera',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam6,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
        // Images[

        // ]
    },
    {
        "id": 'D7',
        "title":'EXE Mini Drone With Sky Controller',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam7,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'D8',
        "title":'Pantony 180 20.0 Megapixel Digital Camera',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"NO-Sale",
        "Type":"Drone",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: cam8,
        "link": "Home",
        "linkM": "Drones & Cameras",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },

]