import speaker1 from '../../../Assets/Imgspeakers/speaker1.webp';
import speaker2 from '../../../Assets/Imgspeakers/speaker2.webp';
import speaker3 from '../../../Assets/Imgspeakers/speaker3.webp';
import speaker4 from '../../../Assets/Imgspeakers/speaker4.webp';
import speaker5 from '../../../Assets/Imgspeakers/speaker5.webp';
import speaker6 from '../../../Assets/Imgspeakers/speaker6.webp';
import speaker7 from '../../../Assets/Imgspeakers/speaker7.webp';
import speaker8 from '../../../Assets/Imgspeakers/speaker8.webp';



export const speakdata=[
    {
        "id": 'S1',
        "title":'Echo Dot (5th Gen, 2022 release) Kids | Designed for kids, with parental controls',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker1,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'S2',
        "title":'JBL FLIP 5, Waterproof Portable Bluetooth Speaker, Black,',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker2,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'S3',
        "title":'Upgraded, Anker Soundcore Bluetooth Speaker Stereo Sound,',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker3,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'S4',
        "title":'Bose SoundLink Flex Bluetooth Portable Speaker, Wireless ',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker4,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'S5',
        "title":'Enther&MAXHUB Bluetooth Speakerphone',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker5,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'S6',
        "title":'Marshall Middleton Portable Bluetooth Speaker,Black',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker6,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'S7',
        "title":'Polk Audio Atrium Speakers with Powerful Bass',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker7,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'S8',
        "title":'Pilu dye Speakers Pair - 2000 Watt Dual ',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: speaker8,
        "link": "Home",
        "linkM": "Speakers",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
]