import imgtab1 from '../../Assets/ImgTablet/imgtab1.webp'
import imgtab2 from '../../Assets/ImgTablet/imgtab2.webp'
import imgtab3 from '../../Assets/ImgTablet/imgtab3.webp'
import imgtab4 from '../../Assets/ImgTablet/imgtab4.webp'
import imgtab5 from '../../Assets/ImgTablet/imgtab5.webp'
import imgtab6 from '../../Assets/ImgTablet/imgtab6.webp'
import imgtab7 from '../../Assets/ImgTablet/imgtab7.webp'
import imgtab8 from '../../Assets/ImgTablet/imgtab8.webp'

export const tabdata =[
    {
        "id": 'T1',
        "title":'Sheer 10.2" Tablet With Wi-Fi , 32GB',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab1,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'T2',
        "title":'JP - Space Tablet 10.4" Wi-Fi 32GB',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab2,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'T3',
        "title":'Pilates 16" Touch Screen Laptop 24GB Memory',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"No-Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab3,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'T4',
        "title":'Ove Tablet FD Plus - 10.3", 32GB',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab4,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'T5',
        "title":'Sheer Pro 7.9-Inch Mini Tablet',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"No-Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab5,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'T6',
        "title":'Ocean Pro 11 - 12.3" Touch Screen',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"No-Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab6,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'T7',
        "title":'Corr Playtime 10.3", 32GB With Wi-Fi',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab7,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'T8',
        "title":'Space Tablet S7 - 11”, 128GB Wi-Fi',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale","Sale2":"Sale",
        "Type":"Tablet",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgtab8,
        "link": "Home",
        "linkM": "Tablets",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    }
]