import head1 from '../../../Assets/Imgheadphones/head1.webp';
import head2 from '../../../Assets/Imgheadphones/head2.webp';
import head3 from '../../../Assets/Imgheadphones/head3.webp';
import head4 from '../../../Assets/Imgheadphones/head4.webp';
import head5 from '../../../Assets/Imgheadphones/head5.webp';
import head6 from '../../../Assets/Imgheadphones/head6.webp';
import head7 from '../../../Assets/Imgheadphones/head7.webp';
import head8 from '../../../Assets/Imgheadphones/head8.webp';


export const headdata = [
    {
        "id": 'head1',
        "title":'UOWGA Active Noise Cancelling Headphones, Wireless Over-Ear Bluetooth Headphones',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head1,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'head2',
        "title":'Rand McNally ClearDryve 180, 2-in-1 Bluetooth',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head2,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'head3',
        "title":'BlueParrott M300-XT SE Mono Bluetooth Wireless Headset with Improved Call Quality for Mobile',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head3,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'head4',
        "title":'Poly Voyager Focus UC Wireless  for Computer w/Charge Stand (Plantronics) - Active',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head4,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'head5',
        "title":'Flexible noise canceling boom with dual microphone Acoustic Fence technology',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head5,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'head6',
        "title":'Jabra Elite 4 True Wireless Earbuds Headphones ',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head6,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'head7',
        "title":'Poly Voyager Focus UC Wireless  for Computer w/Charge Stand (Plantronics) - Active',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head7,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'head8',
        "title":'Dual-ear (stereo) headset',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: head8,
        "link": "Home",
        "linkM": "Headphone",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    
]