import imgcomp1 from '../../Assets/Imgcomp/imgcomp1.webp';
import imgcomp2 from '../../Assets/Imgcomp/imgcomp2.webp';
import imgcomp3 from '../../Assets/Imgcomp/imgcomp3.webp';
import imgcomp4 from '../../Assets/Imgcomp/imgcomp4.webp';
import imgcomp5 from '../../Assets/Imgcomp/imgcomp5.webp';
import imgcomp6 from '../../Assets/Imgcomp/imgcomp6.webp';
import imgcomp7 from '../../Assets/Imgcomp/imgcomp7.webp';
import imgcomp8 from '../../Assets/Imgcomp/imgcomp8.webp';

export const compdata = [
    {
        "id": 'C1',
        "title":'Pilates 14 " Touch Screen Laptop 12GB Memory',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp1,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
        "images": [
            "https://i.dummyjson.com/data/products/1/1.jpg",
            "https://i.dummyjson.com/data/products/1/2.jpg",
            "https://i.dummyjson.com/data/products/1/3.jpg",
            "https://i.dummyjson.com/data/products/1/4.jpg",
            "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
          ]

    },
    {
        "id": 'C2',
        "title":'Pilates 16" Touch Screen Laptop 24GB Memory',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp2,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
    {
        "id": 'C3',
        "title":'JP Gaming Laptop 15.6" Laptop 256GB',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp3,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    }, {
        "id": 'C4',
        "title":'Corr Desktop 12GB Memory, WiFi, Bluetooth, Keyboard, Mouse',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp4,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    }, {
        "id": 'C5',
        "title":'Corr Desktop 24GB Memory + 29" Screen Keyboard & Mouse',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp5,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    }, {
        "id": 'C6',
        "title":'Pilates 16" Touch Screen Laptop 12GB Memory',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp6,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    }, {
        "id": 'C7',
        "title":'MSP 14" Laptop 16GB Memory, Carbon Gray',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp7,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    }, {
        "id": 'C8',
        "title":'JP 29" LED Wide FHD Monitor',
        "quantity":0,
        "price": "$85",
        "discprice":"$70",
        "Sale":"Sale",
        "description": "I'm a product description. This is a great place to 'sell' your product and grab buyers' attention. Describe your product clearly and concisely. Use unique keywords. Write your own description instead of using manufacturers' copy.",
        "Infohead":"Product Info",
        "Infodetail":"I'm a product detail. I'm a great place to add more information about your product such as sizing, material, care and cleaning instructions. This is also a great space to write what makes this product special and how your customers can benefit from this item.",
        "Return":"Return&Refund Policy",
        "ReturnDescrip":"I’m a Return and Refund policy. I’m a great place to let your customers know what to do in case they are dissatisfied with their purchase. Having a straightforward refund or exchange policy is a great way to build trust and reassure your customers that they can buy with confidence.",
        "Shipinfo":"Ship Info",
        "ShipDecrip":"I'm a shipping policy. I'm a great place to add more information about your shipping methods, packaging and cost. Providing straightforward information about your shipping policy is a great way to build trust and reassure your customers that they can buy from you with confidence.",
        thumbnail: imgcomp8,
        "link": "Home",
        "linkM": "Computer",
        "SKU":"SKU : 057",
        "Prev":"Prev",
        "Next":"Next",
    },
]